# Site settings
title: Pete McWilliams
description: >-
  Christ Follower, Family Man, Outdoors Enthusiast, Technologist
baseurl: ""
url: http://petemcw.com
google_analytics: UA-17039579-1

author:
  name: Pete McWilliams
  # email: petemcw@protonmail.com
  twitter_username: petemcw
  instagram_username: petemcw
  github_username: petemcw
  linkedin_username: petemcw

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
pagination:
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
